# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: cosmos/staking/module/v1/module.proto
# plugin: python-betterproto
# This file has been @generated

from dataclasses import dataclass
from typing import List

import betterproto


@dataclass(eq=False, repr=False)
class Module(betterproto.Message):
    """Module is the config object of the staking module."""

    hooks_order: List[str] = betterproto.string_field(1)
    """
    hooks_order specifies the order of staking hooks and should be a list
     of module names which provide a staking hooks instance. If no order is
     provided, then hooks will be applied in alphabetical order of module names.
    """

    authority: str = betterproto.string_field(2)
    """
    authority defines the custom module authority. If not set, defaults to the governance module.
    """
