# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: cosmos/query/v1/query.proto
# plugin: python-betterproto
# This file has been @generated

from dataclasses import dataclass

import betterproto
