# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: layer/bridge/module/module.proto
# plugin: python-betterproto
# This file has been @generated

from dataclasses import dataclass

import betterproto


@dataclass(eq=False, repr=False)
class Module(betterproto.Message):
    """Module is the config object for the module."""

    pass
